repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.15.5
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix]
      # Run the formatter.
      - id: ruff-format
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.2
    hooks:
      - id: codespell
        args:
          - --quiet-level=2
  - repo: local
    hooks:
    - id: mypy
      name: mypy src
      entry: uv run mypy
      language: system
      require_serial: true
      args:
        - --strict
        # - -v
      files: ^(src)/.+\.py$
    - id: mypy tests
      name: mypy tests
      entry: uv run mypy
      language: system
      require_serial: true
      args:
        - --strict
        # - -v
      files: ^(tests)/.+\.py$
