[project]
name = "lcn2mqtt"
version = "0.1.0"
description = "Bridge between LCN (Local Control Network) and MQTT"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pydantic>=2.13.4",
    "pypck>=0.9.14",
    "aiomqtt>=2.3.0",
    "pydantic-settings>=2.14.1",
    "pyyaml>=6.0",
    "pre-commit>=4.6.0",
]

[project.scripts]
lcn2mqtt = "lcn2mqtt.__main__:main"

[build-system]
requires = ["uv_build>=0.10.7,<0.11.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "mypy>=1.19.1",
    "pre-commit>=4.5.1",
    "pytest>=9.0.2",
    "pytest-asyncio>=1.4.0",
    "syrupy>=5.3.4",
    "types-pyyaml>=6.0.12.20260518",
]

[project.urls]
"Source Code" = "https://github.com/alengwenus/lcn2mqtt"
"Bug Reports" = "https://github.com/alengwenus/lcn2mqtt/issues"

[tool.pytest.ini_options]
asyncio_mode = "auto"

[tool.ruff]
cache-dir = ".cache/ruff"

[tool.mypy]
cache_dir = ".cache/mypy"
